# Generated by Django 5.0.14 on 2026-09-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NIÑO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=64)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('especializacion', models.CharField(choices=[('P', 'psicopedagogo'), ('T', 'Trastornos de la escritura'), ('N', 'neuroeducación aplicada al TDAH')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('seccion', models.CharField(choices=[('M', 'Matutina'), ('V', 'Vespertina')], max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('periodo', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('niños', models.ManyToManyField(related_name='cursos', to='NIÑO.niño')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PROFESOR.profesor')),
            ],
        ),
    ]
