# Generated by Django 5.0.14 on 2026-09-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0002_alter_profesor_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='especializacion',
        ),
    ]
