# Generated by Django 5.0.14 on 2026-09-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=64)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('especialidad', models.CharField(choices=[('D', 'Disgrafia'), ('T', 'TDA'), ('DC', 'Discalculia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonido_activado', models.BooleanField(default=True)),
                ('texto_grande', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='NIÑO.niño')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoCartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desbloqueado', models.IntegerField(default=1)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NIÑO.niño')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoDiscalculia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desbloqueado', models.IntegerField(default=1)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NIÑO.niño')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoNiño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_desbloqueado', models.IntegerField(default=1)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('niño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='NIÑO.niño')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distracciones', models.IntegerField(blank=True, help_text='Cantidad de distracciones detectadas', null=True)),
                ('somnolencias', models.IntegerField(blank=True, null=True)),
                ('tiempos_somnolencia', models.JSONField(blank=True, null=True)),
                ('tiempos_distraccion', models.JSONField(blank=True, null=True)),
                ('frames_somnolencia', models.JSONField(blank=True, null=True)),
                ('frames_distraccion', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('duracion_evaluacion', models.DurationField(blank=True, help_text='Duración total de la evaluación', null=True)),
                ('comentario', models.TextField(blank=True, max_length=500, null=True)),
                ('niño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='NIÑO.niño')),
            ],
        ),
    ]
