# Generated by Django 5.0.14 on 2026-09-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niño',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
