# Generated by Django 5.0.14 on 2026-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0002_alter_niño_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='niño',
            name='avatar_accesorio',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='niño',
            name='avatar_camisa',
            field=models.CharField(default='camisa_roja', max_length=20),
        ),
        migrations.AddField(
            model_name='niño',
            name='avatar_pantalon',
            field=models.CharField(default='pantalon_azul', max_length=20),
        ),
        migrations.AddField(
            model_name='niño',
            name='avatar_zapatos',
            field=models.CharField(default='zapatos_blancos', max_length=20),
        ),
    ]
